version: '3.4'

services:
  db:
    image: postgres:16
    container_name: truesneakers_postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=tenis123
      - POSTGRES_DB=truesneakersdb
    ports:
    - "5440:5432"
    volumes:
      - sneakers_data:/var/lib/postgresql/data

volumes:
  sneakers_data: {}